# Generated by Django 4.0.1 on 2022-02-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonoapp', '0002_post_sub_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
