# Generated by Django 4.0.1 on 2022-02-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonoapp', '0003_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
